[package]
name = "weather-buf"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.9.0"
clap = { version = "4.5.23", features = ["derive"] }
prost = "0.13.4"
rand = "0.8.5"

[build-dependencies]
prost-build = "0.13.4"
